config/routes.rb
Rails.application.routes.draw do
  devise_for :users #使用Devise建立User model時產生的
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #前台只能瀏覽餐廳資料
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy] #Nested Resources

    #自訂路由：最新動態和優惠活動都是針對Restaurant，所以放在resources :restaurants區塊中
    collection do #Collection: 用來操作model內全部的資料，因次不需要傳入ID
      get :feeds #瀏覽所有餐廳的最新動態

      get :tops #瀏覽top10人氣餐廳(加入favorite數最高)
    end

    member do #Member: 用來操作model裡的單一資料，因此需要傳入ID來指定單一個record
      get :dashboard #瀏覽個別餐廳的Dashboard(優惠活動)

      # 因為 favorite / unfavorite action 不需要樣板，所以我們習慣使用 POST，而不是 GET
      post :favorite
      post :unfavorite
      
      post :like
      post :unlike
    end
  end


  resources :users, only: [:index, :show, :edit, :update] #User profile
  resources :categories, only: :show
  root "restaurants#index"

  resources :followships, only: [:create, :destroy]

  namespace :admin do
    resources :restaurants #會產生一組URL Helper和網址 對應到不同的Action
    resources :categories
    root "restaurants#index"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #「使用者評論很多餐廳」的多對多關聯
  has_many :comments, dependent: :destroy #刪除user時, 刪除關聯的comments
  has_many :restaurants, through: :comments #透過此設定Rails會知道comments table扮演了Join Table的角色

  #「使用者收藏很多餐廳」的多對多關聯
  has_many :favorites, dependent: :destroy #刪除user時, 其相關favorite物件也一並被刪除
  has_many :favorited_restaurants, through: :favorites, source: :restaurant
    # 在使用者評論過的餐廳中已用過 has_many :restaurants 的設定
    # 所以這裡不能用相同設定,否則使用object.restaurants方法時會無法分辨你是要查詢評論過的餐廳還是收藏的餐廳
    # 因此收藏關係指定自定義的名稱,另加來源source告知model name

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurants

  has_many :followships, dependent: :destroy #一個User擁有很多追蹤記錄(followships)
  has_many :followings, through: :followships #一個User透過追蹤記錄追蹤很多其他User(followings)
  #注意：如果關聯設定了:through, :dependent就會被忽略, 所以只在其中一行做設定

  mount_uploader :avatar, AvatarUploader

  validates_presence_of :name #註冊時name必填

  def admin?
    self.role == "admin" #會回傳True或False
  end

  def following?(user) #檢查追蹤記錄是否已經存在
    self.followings.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    #@user = User.find(params[:id])
    @commented_restaurants = @user.restaurants #取得使用者評論過的餐廳資料
  end

  def edit
    #@user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    #@user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <h2>Edit Profile</h2>

  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :intro, "自我介紹" %>
      <%= f.text_area :intro, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :avatar, "大頭照上傳" %>
      <%= image_tag @user.avatar.url, width: '150px' if @user.avatar? %>
      <%= f.file_field :avatar %>
    </div>
    
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
    </div>

  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <ul class="nav nav-tabs">
      <li role="presentation"><%= link_to '首頁', restaurants_path %></li>
      <li role="presentation"><%= link_to '最新動態', feeds_restaurants_path %></li>
      <li role="presentation"><%= link_to 'Top10人氣餐廳', tops_restaurants_path %></li>
      <li role="presentation" class="active"><%= link_to '美食達人', users_path %></li>
    </ul>

  </div>
</div>


<div class="container">
  <div class="row">

    <div class="col-md-12">
      <div class="page-header">
        <h2>美食達人</h2>
      </div>
    </div>
  
    <% @users.each do |user| %>
      <div class="col-md-3 col-sm-4 col-xs-6 text-center user-item">
        <%= link_to user_path(user) do %>

          <% if user.avatar? %>
            <%= image_tag user.avatar.url, class: "img-rounded" %>
          <% else %>
            <%= image_tag ("128x128.png"), class: "img-rounded" %>
          <% end %>
          
          <br>
          
          <h5><%= user.name %></h5>

        <% end %>
        
        <%# 呼叫follow partial %>
        <%= render partial: "shared/follow", locals: {user: user} %> 
      </div>
    <% end %>
      
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <table>
    <tr>
      <td rowspan="4" class="col-md-4">
        <% if @user.avatar? %>
          <%= image_tag @user.avatar.url, width: '200px' %>
        <% else %>
          <%= image_tag ("800x600.png"), width: '200px' %>
        <% end %>
      </td>
      <td>
        <% if @user.name? %>
          <h4><%= @user.name %></h4>
        <% else %>
          <h4>User Name</h4>
        <% end %>
      </td>
    </tr>
      <td class="text-muted"><%= @user.email %></td>
    </tr>
    <tr>
      <td>
        <% if @user.intro? %>
          <%= simple_format(@user.intro) %>
        <% else %>
          <p><em>About me...</em></p>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <% if @user.email == current_user.email %><%# 重要 %>
          <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-primary" %>
        <% end %>
      </td>
    </tr>
  </table>

  <br>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @commented_restaurants.uniq.count %> 間評論過的餐廳</h3>
    </div>
    <div class="panel-body">

      <% @commented_restaurants.uniq.each do |restaurant| %><%# uniq 不顯示重複的餐廳 %>
        <%= link_to restaurant_path(restaurant) do %>
          <div class="col-md-4">
          <div class="my-restaurant">
            <% if restaurant.image? %>
              <%= image_tag restaurant.image.url, height: '200px' %>
            <% else %>
              <%= image_tag ("800x600.png"), height: '200px' %>
            <% end %>

            <p><%= restaurant.name %></p>
          </div>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>

</div>