config/routes.rb
Rails.application.routes.draw do
  devise_for :users #使用Devise建立User model時產生的
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #前台只能瀏覽餐廳資料
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy] #Nested Resources

    #自訂路由：最新動態和優惠活動都是針對Restaurant，所以放在resources :restaurants區塊中
    collection do #Collection: 用來操作model內全部的資料，因次不需要傳入ID
      get :feeds #瀏覽所有餐廳的最新動態

      get :tops #瀏覽top10人氣餐廳(加入favorite數最高)
    end

    member do #Member: 用來操作model裡的單一資料，因此需要傳入ID來指定單一個record
      get :dashboard #瀏覽個別餐廳的Dashboard(優惠活動)

      # 因為 favorite / unfavorite action 不需要樣板，所以我們習慣使用 POST，而不是 GET
      post :favorite
      post :unfavorite
      
      post :like
      post :unlike
    end
  end


  resources :users, only: [:index, :show, :edit, :update] #User profile
  resources :categories, only: :show
  root "restaurants#index"

  resources :followships, only: [:create, :destroy]

  namespace :admin do
    resources :restaurants #會產生一組URL Helper和網址 對應到不同的Action
    resources :categories
    root "restaurants#index"
  end
end

app/views/shared/_favorite.html.erb
<% if restaurant.is_favorited?(current_user) %>
  <%= link_to 'Unfavorite', unfavorite_restaurant_path(restaurant), method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to 'Favorite', favorite_restaurant_path(restaurant), method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_follow.html.erb
<% if user != current_user %><%# 只有當user不是current_user時才會顯示按鈕 %>
        
  <% if current_user.following?(user) %>
    <%= link_to 'Unfollow', followship_path(user), method: :delete, class: "btn btn-default" %>
  <% else %>
    <%= link_to 'Follow', followships_path(following_id: user.id), method: :post, class: "btn btn-default" %>
  <% end %>
      
<% end %>

app/views/shared/_like.html.erb
<% if restaurant.is_liked?(current_user) %>
  <%= link_to 'Unlike', unlike_restaurant_path(restaurant), method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to 'Like', like_restaurant_path(restaurant), method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_restaurant_list.html.erb
<% @restaurants.each do |restaurant| %>
    <div class="col-sm-6 col-md-4">
      <div class="restaurant-item">

        <%= link_to restaurant_path(restaurant) do %><%# 點擊圖片可進入show頁面 %>
          <% if restaurant.image? %>
            <%= image_tag restaurant.image.url, class: "img-responsive center-block" %>
          <% else %>
            <%= image_tag ("800x600.png"), class: "img-responsive center-block" %>
            <%# 替代圖片放在app/assets/images中 %>
          <% end %>
        <% end %>
          
        <div class="caption">
          <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
          <%# 點擊餐廳名稱可進入show頁面 %>
          <div class="category-label">
            <p class="label label-default"><%= restaurant.category.name %></p>
          </div>
          <p><%= truncate(restaurant.description, length: 80) %></p>
          <%# truncate方法用來截段文字,用length將長度限定在80個字母 %>   
          <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %> 
          <%= render partial: "shared/like", locals: {restaurant: restaurant} %>
        </div>

      </div>
    </div>
<% end %>

<div class="col-sm-12 col-md-12">
  <div class="text-center">
    <%= paginate @restaurants %>
  </div>
</div>