config/routes.rb
Rails.application.routes.draw do
  devise_for :users #使用Devise建立User model時產生的
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #前台只能瀏覽餐廳資料
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy] #Nested Resources

    #自訂路由：最新動態和優惠活動都是針對Restaurant，所以放在resources :restaurants區塊中
    collection do #Collection: 用來操作model內全部的資料，因次不需要傳入ID
      get :feeds #瀏覽所有餐廳的最新動態

      get :tops #瀏覽top10人氣餐廳(加入favorite數最高)
    end

    member do #Member: 用來操作model裡的單一資料，因此需要傳入ID來指定單一個record
      get :dashboard #瀏覽個別餐廳的Dashboard(優惠活動)

      # 因為 favorite / unfavorite action 不需要樣板，所以我們習慣使用 POST，而不是 GET
      post :favorite
      post :unfavorite
      
      post :like
      post :unlike
    end
  end


  resources :users, only: [:index, :show, :edit, :update] #User profile
  resources :categories, only: :show
  root "restaurants#index"

  resources :followships, only: [:create, :destroy]

  namespace :admin do
    resources :restaurants #會產生一組URL Helper和網址 對應到不同的Action
    resources :categories
    root "restaurants#index"
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  mount_uploader :image, PhotoUploader

  #加入驗證程序,將name設為必填,若使用者未填寫餐廳名稱,就不會將這筆資料送進資料庫
  #與資料庫的互動由Model負責,所以寫在Restaurant Model中
  validates_presence_of :name

  belongs_to :category
  has_many :comments, dependent: :destroy #刪除Restaurant時,一併刪除關聯的評論

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

  #def count_favorites >> 用counter_cache方法代替（寫在favorite.rb)
    #self.favorites_count = self.favorites.count
    #self.save
  #end
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  #before_action :authenticate_user! 
    #Devise提供的驗證方法,移到application_controller.rb
  #before_action :authenticate_admin 
    #自己寫的方法,(寫在superclass的ApplicationController中>>移到BaseController)
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]


  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
    #原為@restaurant = Restaurant.all
    #利用Kaminari gem完成分頁功能
    #page 會根據分頁序數來篩選對應資料
    #per 決定一頁有幾筆資料
    #params[:page] 取得分頁數值,page方法就知道要讀取第幾頁的資料
  end

  def new
    @restaurant = Restaurant.new
    #建立新的餐廳實例@restaurant,然後將這個實例存入變數
    #Restaurant.new會透過Restaurant Model呼叫new方法,產生一個物件實例,在restaurants table建立新的一列空資料
    #將新建立的@restaurant送進View樣板,讓使用者填寫表單
  end

  def create
    @restaurant = Restaurant.new(restaurant_params) #透過params(private method)拿到使用者從表單輸入的資料
    #Restaurant.new會透過Restaurant Model再次呼叫new方法,把表單資料寫入@restaurant
    #呼叫save方法將資料存入
    if @restaurant.save #如果資料成功存入(表示驗證成功)
      flash[:notice] = "restaurant was successfully created"
      #flash方法的消息會保存到下一个action，和redirct_to方法一起使用
      redirect_to admin_restaurants_path #導回後台Index
    else #驗證失敗
      flash.now[:alert] = "restaurant was failed to create"
      #flash.now方法的消息只會在當前視窗顯示，不會保存到下一个action，和render方法一起使用
      render :new #留在new編輯畫面(render會保留原本有填入的欄位資料)
    end
  end

  def show
    #before_action :set_restaurant
  end

  def edit
    #before_action :set_restaurant
  end

  def update
    #before_action :set_restaurant
    if @restaurant.update(restaurant_params)
      flash[:notice] = "restaurant was successfully updated"
      redirect_to admin_restaurant_path(@restaurant)
    else
      flash.now[:alert] = "restaurant was failed to update"
      render :edit
    end
  end

  def destroy
    #before_action :set_restaurant
    @restaurant.destroy
    redirect_to admin_restaurants_path #回到index
    flash[:alert] = "restaurant was deleted"
  end


  private

  #Strong Parameters: 在讀取表單資料時，基於安全考量，必須在參數傳入時多做一層處理
  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
    #使用require(:restaurant)拿出表單資料
    #透過permit過濾資料,防止有人傳入不相關的惡意資訊
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  #before_action :authenticate_user!
    #移到application_controller.rb
  before_action :set_restaurant, only: [:dashboard, :favorite, :unfavorite, :like, :unlike]

  #前台首頁
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end

  #最新動態
  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10) #新到舊,只顯示10筆
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  #TOP10人氣餐廳
  def tops
    @top_restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end

  def dashboard
    #@restaurant = Restaurant.find(params[:id])
  end

  def favorite
    #@restaurant = Restaurant.find(params[:id])
    #如果已在我的最愛(避免重複加入favorites table)
    if @restaurant.is_favorited?(current_user)
      #跳出提示訊息表示已加入
      flash[:alert] = "already in favorite list"
    else
      @restaurant.favorites.create!(user: current_user) #寫法有很多種,請參考教案
      #@restaurant.count_favorites >> 用counter_cache方法代替（寫在favorite.rb)
    end
    redirect_back(fallback_location: root_path) #回上頁
  end

  def unfavorite
    #@restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all #因為上述程式碼查找出來會是一個集合,所以要用destroy_all而不是destroy
    #@restaurant.count_favorites >> 用counter_cache方法代替（寫在favorite.rb)
    redirect_back(fallback_location: root_path)
  end

  def like
    #@restaurant = Restaurant.find(params[:id])
    if @restaurant.is_liked?(current_user)
      flash[:alert] = "already liked"
    else
      @restaurant.likes.create!(user: current_user)
    end
    redirect_back(fallback_location: root_path)
  end

  def unlike
    #@restaurant = Restaurant.find(params[:id])
    likes = Like.where(restaurant: @restaurant, user: current_user)
    likes.destroy_all
    redirect_back(fallback_location: root_path)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<div class="container">

  <%# 讀取@restaurant.errors的內容幫助使用者了解為何被退回 %>
  <% if @restaurant.errors.any? %>
    <h2>We have some errors here!</h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>


  <%= form_for [:admin, @restaurant] do |f| %>
  <%# 用中括號標示來告訴Rails要去namespace找相對應的路徑 %>
    <div class="form-group">
      <%= f.label :category %>
      <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "請選擇"}, {class: "form-control"} %>
    </div>

    <div class="form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>  

    <div class="form-group">
      <%= f.label :tel, "Tel" %>
      <%= f.text_field :tel, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :address, "Address" %>
      <%= f.text_field :address, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :opening_hours, "Opening Hours" %>
      <%= f.text_field :opening_hours, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :image, "Photo" %>
      <%= image_tag @restaurant.image.url, width: '150px' if @restaurant.image? %>
      <%= f.file_field :image %>
    </div>
    
    <div class="form-group">
    <%= f.submit class: "btn btn-primary" %> &emsp;
    <%= link_to 'Go to Index', admin_restaurants_path %>
    </div>
  <% end %>

</div>

app/views/admin/restaurants/edit.html.erb
<%# 原程式碼都移到_form.html.erb(與new.html.erb共用) %>
<%= render partial: "form" %>
<%# partial: 指定去找_開頭的檔案, "form" 指定了form %>

app/views/admin/restaurants/index.html.erb
<div class="container">
  <h2>
    餐廳後台
    <%= link_to 'Create New Restaurant', new_admin_restaurant_path, 
      class: "btn btn-warning" %>
  </h2>

  <div><%# 切換後台餐廳總表/餐廳分類總表 %>
    <%= link_to 'Restaurant', admin_restaurants_path %> |
    <%= link_to 'Categories', admin_categories_path %>
  </div>

  <br>

  <div class="col-md-12">
    
    <table class="table table-striped table-bordered">
      <tr>
        <th>#</th>
        <th>Category</th>
        <th>Restaurant Name</th>
        <th></th>
      </tr>  
      
      <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.id %></td>
        <td>[<%= restaurant.category.name %>]</td>
        <td><%= restaurant.name %></td>
        <td>
          <%= link_to 'Show', admin_restaurant_path(restaurant) %> &emsp;
          <%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %> &emsp;
          <%= link_to 'Delete', admin_restaurant_path(restaurant), method: :delete, data: {confirm:"Are you sure?"} %>
        </td>
      </tr>
      <% end %>
    </table>

  </div>

  <%= paginate @restaurants %><%# 分頁導覽器 %>
  <br>
  <br>
</div>

app/views/admin/restaurants/new.html.erb
<%# 讀取@restaurant.errors的內容幫助使用者了解為何被退回 %>
<% if @restaurant.errors.any? %>
  <h2>We have some errors here!</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for [:admin, @restaurant] do |f| %>
<%# 用中括號標示來告訴Rails要去namespace找相對應的路徑 %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %>

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>

  <%= f.label :opening_hours, "Opening Hours" %>
  <%= f.text_field :opening_hours %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

<%= link_to 'Back to Index', admin_restaurants_path %>

app/views/admin/restaurants/show.html.erb
<div class="container">

  <h2><%= @restaurant.name %></h2>
  <h5>[<%= @restaurant.category.name %>]</h5>

  <table class="table table-striped table-bordered">
    <tr>
      <td class="col-md-4">
        <% if @restaurant.image? %>
          <%= image_tag @restaurant.image.url, width: '400px' %>
        <% else %>
          <%= image_tag ("800x600.png"), width: '400px' %>
        <% end %>
      </td>

      <td class="col-md-8">
        <b>Opening Hours: </b><%= @restaurant.opening_hours %><br>
        <br>
        <b>Tel: </b><%= @restaurant.tel %><br>
        <br>
        <b>Address: </b><%= @restaurant.address %><br>
        <br>
        <b>Description: </b><%= simple_format(@restaurant.description) %>
      </td>
    </tr>
  </table>

  <%= link_to 'Edit', edit_admin_restaurant_path, class: "btn btn-warning" %>
  <%= link_to 'Delete', admin_restaurant_path, method: :delete, data: {confirm:"Are you sure?"}, class: "btn btn-warning" %>
  <%= link_to 'Back to Index', admin_restaurants_path, class: "btn btn-primary" %>
  <br>
  <br>
  <br>

</div>